In [2]:
import numpy as np

### EJERCICIO 1

In [27]:
#Crea un array con los numeros del 0 al 9
array09 = np.arange(10)#usamos np.arange para dar un rango de valor maximo empieza en 0 por ello le damos (10) como valor para añadir hasta el valor 9
print(array09)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
#Crea un array dde ceros de tamaño 5 y otro de unos de tamaño 5
array5 = np.zeros(5)#usamos np.zero para dar valor "0" a cada elemento del array
print(array5)
array5 = np.ones(5)#usamos np.uno para dar valor "1" a cada elemento del array
print(array5)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [23]:
#Crea un array con 20 valores entre 0 y 1 usando linspace
array20 = np.linspace(0,1,20) #Usamos np.linspace para dar un valor entre dos valores ("n valor inicio","n valor final","n de valores totales")
print(array20)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


### EJERCICIO 2

In [32]:
#Para cada array creado en el ejercicio anterior, muestra: forma(shape), numero de dimensiones (ndim), tipo de dato (dtype)
print("ARRAY09")
print(np.shape(array09))
print(np.ndim(array09))
print("ARRAY5")
print(np.shape(array5))
print(np.ndim(array5))
print("ARRAY20")
print(np.shape(array20))
print(np.ndim(array20))

ARRAY09
(10,)
1
ARRAY5
(5,)
1
ARRAY20
(20,)
1


### EJERCICIO 3

In [54]:
#Crea los siguientes arrays en NumPy
array1 = [88,23,39,41]
array2 = np.array([[76.4,21.7,38.4],[41.2,52.8,68.9]])
array3 = np.array([[12],
          [4],
          [9],
          [8]])
print("ARRAY1")
print(array1)
#print(np.array(array2).reshape(2,3))
print("ARRAY2")
print(array2)
print("ARRAY3")
print(array3)

ARRAY1
[88, 23, 39, 41]
ARRAY2
[[76.4 21.7 38.4]
 [41.2 52.8 68.9]]
ARRAY3
[[12]
 [ 4]
 [ 9]
 [ 8]]


### EJERCICIO 4

In [8]:
#Crea una matriz 2x6 con valores del 1 al 12
array26 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(array26)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [29]:
#Transforma en:
#a) Una matriz 3x4
array34 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array34)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
#b)Una matriz 4x3
array43 = np.array([[1,2,3,],[4,5,6],[7,8,9],[10,11,12]])
print(array43)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#c)Su traspuesta


In [83]:
#d)Una matriz diagonal con los valores de la primera fila
array = np.array([1,2,3,4,5,6])
array = np.diag(array)
print(array)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


### EJERCICIO 5

In [15]:
#Selecciona la primera columna.
print(array26[:,0])

[1 7]


In [19]:
#Selecciona la submatriz de las dos últimas filas y dos últimas columnas
print(array26[-2,:],array26[-1,:],array26[:,-2],array26[:,-1])

[1 2 3 4 5 6] [ 7  8  9 10 11 12] [ 5 11] [ 6 12]


### EJERCICIO 6

In [71]:
#Convertir esta matriz:
print("ARRAY BASE")
array6=np.array([[17,12,31],[49,11,51],[21,31,62],[63,75,22]])
print(array6)

#En cada uno de estas:
print("PRIMERA")
#1:
array1 = np.copy(array6)
array1 = np.delete(array1,3,axis=0)
array1 = np.insert(array1,3,[63, 75, 22],axis=1)
print(array1)
print("SEGUNDA")
#1:
array1 = np.copy(array6)
array1 = np.delete(array1,3,axis=0)
array1 = np.delete(array1,1,axis=0)
array1 = np.insert(array1,1,[49],axis=0)
array1 = np.insert(array1,3,[63],axis=1)
print(array1)

ARRAY BASE
[[17 12 31]
 [49 11 51]
 [21 31 62]
 [63 75 22]]
PRIMERA
[[17 12 31 63]
 [49 11 51 75]
 [21 31 62 22]]
SEGUNDA
[[17 12 31 63]
 [49 49 49 63]
 [21 31 62 63]]


### EJERCICIO 7

In [139]:
#Partiendo de una matriz de 10 filas y 10 columnas con valores aleatorios
#enteros en el intervalo [0,100] realiza las operaciones necesarias para
#obtener una matriz de las mismas dimensiones donde:
array1010 = np.array(np.random.randint(0,100, size=(10,10)))
print(array1010)

[[79 53 98 84 51 39 27 65 42 84]
 [ 6 46 33 71 55 23 59 56 50 72]
 [27 58 38 64 49 20 77 14 27 33]
 [41  1 33 52 92 11 61  5 53 28]
 [41 48  8  1 91 64 85  5 69 91]
 [81 62  2 57  8 59 91 15 21 85]
 [94  1 30 44 31 69 45 12 99 14]
 [ 9 71 79 21 79 94 32 36  2 50]
 [14 71  3 62 62  1 74 66 94 99]
 [83 94 46 57 42 19 28 30 77 93]]


In [117]:
#Todos los elementos igual a 10 se les suma 200.
array10 = np.copy(array1010)
for i in range(len(array10)):
    for j in range(len(array10[i])):
        if array10[i][j]==10:
            array10[i][j]+=200
print(array10)

[[ 9 37 86 13 72 19 93  3 20 14]
 [50 43 12 12 52 94 93 91 57  2]
 [93 91 14  0 71 25 21 15 55 41]
 [43 40 11 35 65 77 49 84 74 46]
 [38 67 52 23 85 65 56 16 11 48]
 [73 12 32 17 56 85 65 96  8 81]
 [76  2 78 56 20 93 70 54 61 15]
 [67 29 52 99 53 99 55 62 50  5]
 [76 67 68 97  2  4 41 14 64 72]
 [11 85 92 35 61 49 65 45 50 44]]


In [119]:
#Los elementos entre 11 y 50 tengan valor 100.
array9 = np.copy(array1010)
for i in range(len(array9)):
    for j in range(len(array9[i])):
        if array9[i][j]>=11 & array9[i][j]<=50:
            array9[i][j]=100
print(array9)

[[100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]]


In [120]:
#Los elementos mayores que 50 tengan valor 0.
array8 = np.copy(array1010)
for i in range(len(array8)):
    for j in range(len(array8[i])):
        if array8[i][j]>50:
            array8[i][j]=0
print(array8)

[[ 9 37  0 13  0 19  0  3 20 14]
 [50 43 12 12  0  0  0  0  0  2]
 [ 0  0 14  0  0 25 21 15  0 41]
 [43 40 11 35  0  0 49  0  0 46]
 [38  0  0 23  0  0  0 16 11 48]
 [ 0 12 32 17  0  0  0  0  8  0]
 [ 0  2  0  0 20  0  0  0  0 15]
 [ 0 29  0  0  0  0  0  0 50  5]
 [ 0  0  0  0  2  4 41 14  0  0]
 [11  0  0 35  0 49  0 45 50 44]]


In [121]:
#Los elementos menores de 10 tengan el valor 1.
array7 = np.copy(array1010)
for i in range(len(array7)):
    for j in range(len(array7[i])):
        if array7[i][j]<10:
            array7[i][j]=1
print(array7)

[[ 1 37 86 13 72 19 93  1 20 14]
 [50 43 12 12 52 94 93 91 57  1]
 [93 91 14  1 71 25 21 15 55 41]
 [43 40 11 35 65 77 49 84 74 46]
 [38 67 52 23 85 65 56 16 11 48]
 [73 12 32 17 56 85 65 96  1 81]
 [76  1 78 56 20 93 70 54 61 15]
 [67 29 52 99 53 99 55 62 50  1]
 [76 67 68 97  1  1 41 14 64 72]
 [11 85 92 35 61 49 65 45 50 44]]


### EJERCICIO 8

In [126]:
#A partir de la matriz que se generó en el ejercicio anterior:
array8 = np.copy(array1010)

In [131]:
#Cuenta cuántos valores de la matriz final son iguales a 100.
for i in range(len(array8)):
    for j in range(len(array8[i])):
        if array8[i][j]==100:
            count = count+1
print ("Hay ",count," valores iguales a 100")

Hay  0  valores iguales a 100


In [138]:
#Cuenta cuántos son iguales a 0. 
for i in range(len(array8)):
    for j in range(len(array8[i])):
        if array8[i][j]==0:
            count = count+1
print ("Hay ",count," valores iguales a 0")

Hay  0  valores iguales a 0


### EJERCICIO 9

In [11]:
print("ALTURAS")
alturas = np.array([1.74, 1.8, 1.78, 1.68, 1.78, 1.7, 1.74, 1.74, 1.73,
1.79,
 1.78, 1.72, 1.65, 1.78, 1.7, 1.68, 1.79, 1.68, 1.82, 1.72,
 1.75, 1.66, 1.67, 1.79, 1.75, 1.65, 1.78, 1.73, 1.71, 1.81,
 1.73, 1.71, 1.68, 1.74, 1.75, 1.68, 1.74, 1.81, 1.73, 1.82,
 1.8, 1.67, 1.73, 1.7, 1.73, 1.7, 1.81, 1.81, 1.76, 1.82, 1.68,
 1.74, 1.65, 1.8, 1.78, 1.7, 1.68, 1.78, 1.79, 1.73, 1.64, 1.67,
 1.69, 1.74, 1.76, 1.66, 1.66, 1.73, 1.79, 1.81, 1.78, 1.63,
 1.76, 1.72, 1.71, 1.7, 1.62, 1.8, 1.75, 1.8, 1.78, 1.78, 1.76,
 1.65, 1.65, 1.68, 1.74, 1.75, 1.69, 1.75, 1.7, 1.83, 1.64, 1.7,
 1.69, 1.69, 1.64, 1.69, 1.77, 1.8, 1.78, 1.69, 1.7, 1.7, 1.7,
 1.63, 1.73, 1.84, 1.66, 1.78, 1.8, 1.79, 1.78, 1.74, 1.77,
 1.73, 1.77, 1.76, 1.75, 1.8, 1.75, 1.8, 1.79, 1.71, 1.73,
 1.59, 1.76, 1.75, 1.71, 1.76, 1.8, 1.68, 1.74, 1.77, 1.73,
 1.68, 1.63, 1.67])
print(alturas)
print("PESOS")
pesos = np.array([81.4, 88.7, 87.3, 62.7, 81.6, 80.9, 74.6, 84.7, 76.7,
88.3,
 84.6, 74, 57.7, 84.1, 79.7, 63.8, 88.4, 71.2, 87.1, 67, 80.7,
 74.7, 60.5, 85.9, 72.4, 59.7, 87.3, 85.7, 64.1, 91.9, 82.8, 75.7,
 60.2, 73.1, 74.7, 65.9, 80.9, 91.3, 76, 86.8, 80.7, 74.2, 83.1,
 77.8, 84.5, 58.8, 89.5, 87, 84, 89.9, 56.5, 80.2, 61.8, 86.3,
 82.6, 69.4, 65.8, 79.3, 88.1, 78.5, 69.1, 62.5, 74, 74.4, 87.6,
 59.6, 61.4, 83.2, 89.2, 89.2, 103.7, 67.9, 85.4, 69.5, 75.7,
 83.9, 59.5, 87.9, 82.6, 88.1, 86.2, 88.9, 84.4, 58.4, 61.5, 69.2,
 84.2, 78, 81.1, 81.5, 74.7, 90.4, 59.2, 79.3, 65.1, 93, 60.5,
 76.4, 98.8, 89.1, 88.9, 61.1, 76.6, 86, 75.5, 66.9, 79.4, 87.9,
 72.3, 93.8, 89, 90.7, 86.7, 77.6, 85.1, 91.8, 103.2, 91.1, 67,
 86.9, 78.7, 87.1, 85.5, 69.8, 75, 53.9, 99, 93.7, 88, 79.4, 87.6,
 60.4, 82.7, 90.6, 79.8, 61.2, 62.5, 59.7])
print(pesos)

ALTURAS
[1.74 1.8  1.78 1.68 1.78 1.7  1.74 1.74 1.73 1.79 1.78 1.72 1.65 1.78
 1.7  1.68 1.79 1.68 1.82 1.72 1.75 1.66 1.67 1.79 1.75 1.65 1.78 1.73
 1.71 1.81 1.73 1.71 1.68 1.74 1.75 1.68 1.74 1.81 1.73 1.82 1.8  1.67
 1.73 1.7  1.73 1.7  1.81 1.81 1.76 1.82 1.68 1.74 1.65 1.8  1.78 1.7
 1.68 1.78 1.79 1.73 1.64 1.67 1.69 1.74 1.76 1.66 1.66 1.73 1.79 1.81
 1.78 1.63 1.76 1.72 1.71 1.7  1.62 1.8  1.75 1.8  1.78 1.78 1.76 1.65
 1.65 1.68 1.74 1.75 1.69 1.75 1.7  1.83 1.64 1.7  1.69 1.69 1.64 1.69
 1.77 1.8  1.78 1.69 1.7  1.7  1.7  1.63 1.73 1.84 1.66 1.78 1.8  1.79
 1.78 1.74 1.77 1.73 1.77 1.76 1.75 1.8  1.75 1.8  1.79 1.71 1.73 1.59
 1.76 1.75 1.71 1.76 1.8  1.68 1.74 1.77 1.73 1.68 1.63 1.67]
PESOS
[ 81.4  88.7  87.3  62.7  81.6  80.9  74.6  84.7  76.7  88.3  84.6  74.
  57.7  84.1  79.7  63.8  88.4  71.2  87.1  67.   80.7  74.7  60.5  85.9
  72.4  59.7  87.3  85.7  64.1  91.9  82.8  75.7  60.2  73.1  74.7  65.9
  80.9  91.3  76.   86.8  80.7  74.2  83.1  77.8  84.5  58.8  89.5  

In [12]:
#Se pide crear el imc, índice de masa corporal correspondiente a cada alturapeso. 
#Y crear un array de tres columnas donde tengamos, la altura, el peso y el imc.
#La fórmula para el imc es  imc = peso/altura2:
alturasValor=alturas
alturas=alturas*alturas
imc=pesos/alturas
listaimc = np.stack((alturasValor,pesos,imc),axis=1)
print(listaimc)

[[  1.74        81.4         26.8859823 ]
 [  1.8         88.7         27.37654321]
 [  1.78        87.3         27.55333922]
 [  1.68        62.7         22.21513605]
 [  1.78        81.6         25.75432395]
 [  1.7         80.9         27.99307958]
 [  1.74        74.6         24.63997886]
 [  1.74        84.7         27.97595455]
 [  1.73        76.7         25.62731799]
 [  1.79        88.3         27.55844075]
 [  1.78        84.6         26.70117409]
 [  1.72        74.          25.01352082]
 [  1.65        57.7         21.19375574]
 [  1.78        84.1         26.54336574]
 [  1.7         79.7         27.57785467]
 [  1.68        63.8         22.60487528]
 [  1.79        88.4         27.58965076]
 [  1.68        71.2         25.22675737]
 [  1.82        87.1         26.29513344]
 [  1.72        67.          22.64737696]
 [  1.75        80.7         26.35102041]
 [  1.66        74.7         27.10843373]
 [  1.67        60.5         21.69314066]
 [  1.79        85.9         26.80

### EJERCICIO 10

In [13]:
#A partir de la matriz resultante del ejercicio anterior, calcula lo siguiente:
lista = np.copy(listaimc)
print(lista)

[[  1.74        81.4         26.8859823 ]
 [  1.8         88.7         27.37654321]
 [  1.78        87.3         27.55333922]
 [  1.68        62.7         22.21513605]
 [  1.78        81.6         25.75432395]
 [  1.7         80.9         27.99307958]
 [  1.74        74.6         24.63997886]
 [  1.74        84.7         27.97595455]
 [  1.73        76.7         25.62731799]
 [  1.79        88.3         27.55844075]
 [  1.78        84.6         26.70117409]
 [  1.72        74.          25.01352082]
 [  1.65        57.7         21.19375574]
 [  1.78        84.1         26.54336574]
 [  1.7         79.7         27.57785467]
 [  1.68        63.8         22.60487528]
 [  1.79        88.4         27.58965076]
 [  1.68        71.2         25.22675737]
 [  1.82        87.1         26.29513344]
 [  1.72        67.          22.64737696]
 [  1.75        80.7         26.35102041]
 [  1.66        74.7         27.10843373]
 [  1.67        60.5         21.69314066]
 [  1.79        85.9         26.80

In [14]:
#Calcula el IMC medio del grupo.    
media = lista.mean(axis=0)
print("IMC MEDIO ES:")
print(media[2])

IMC MEDIO ES:
26.0032024404846


In [23]:
#Cuenta cuántas personas tienen IMC < 18.5 (bajo peso), 18.5–24.9
#(normal), 25–29.9 (sobrepeso) y ≥30 (obesidad).
countBP = 0
countN = 0
countO = 0
for i in range(len(lista)):
    if lista[i][2]<18.5:
        countBP = countBP+1
    elif lista[i][2]>=18.5 and lista[i][2]<=24.9:
        countN = countN+1
    elif lista[i][2]>=25  and lista[i][2]>=30:
        countO = countO+1
print("Hay ",countBP," Bajo Peso ",countN," Peso Normal ",countO," Obeso")
        

Hay  0  Bajo Peso  38  Peso Normal  8  Obeso
