### EJERCICIO 11 - Productividad y salarios en una empresa tecnológica

In [1]:
import numpy as np

In [22]:
#Se dispone de los datos de 200 000 empleados de una empresa tecnológica.
#Cada empleado tiene asignado:
#  Sueldo base anual (salarios)
arraySalario=np.random.randint(1,100, size=200000)
#  Número de proyectos completados (proyectos)
arrayProyecto=np.random.randint(1,10, size=200000)
#  Horas trabajadas al año (horas)
arrayHora=np.random.randint(1,80, size=200000)
#A partir de estos datos:
datosEmpleados = np.stack((arraySalario,arrayProyecto,arrayHora),axis=1)
print(datosEmpleados)

[[34  9  5]
 [96  4 17]
 [52  1 50]
 ...
 [41  4 55]
 [45  3 65]
 [12  5 68]]


In [28]:
#1. Calcula la productividad = proyectos / horas
productividad = arrayProyecto/arrayHora
datosEmpleados = np.stack((arraySalario,arrayProyecto,arrayHora,productividad),axis=1)
print(datosEmpleados)

[1.8        0.23529412 0.02       ... 0.07272727 0.04615385 0.07352941]
[[3.40000000e+01 9.00000000e+00 5.00000000e+00 1.80000000e+00]
 [9.60000000e+01 4.00000000e+00 1.70000000e+01 2.35294118e-01]
 [5.20000000e+01 1.00000000e+00 5.00000000e+01 2.00000000e-02]
 ...
 [4.10000000e+01 4.00000000e+00 5.50000000e+01 7.27272727e-02]
 [4.50000000e+01 3.00000000e+00 6.50000000e+01 4.61538462e-02]
 [1.20000000e+01 5.00000000e+00 6.80000000e+01 7.35294118e-02]]


In [29]:
#2. Calcula la bonificación = productividad × salario × 0.05
bonificacion = productividad*arraySalario*0.05
datosEmpleados = np.stack((arraySalario,arrayProyecto,arrayHora,productividad,bonificacion),axis=1)
print(datosEmpleados)

[3.06       1.12941176 0.052      ... 0.14909091 0.10384615 0.04411765]
[[3.40000000e+01 9.00000000e+00 5.00000000e+00 1.80000000e+00
  3.06000000e+00]
 [9.60000000e+01 4.00000000e+00 1.70000000e+01 2.35294118e-01
  1.12941176e+00]
 [5.20000000e+01 1.00000000e+00 5.00000000e+01 2.00000000e-02
  5.20000000e-02]
 ...
 [4.10000000e+01 4.00000000e+00 5.50000000e+01 7.27272727e-02
  1.49090909e-01]
 [4.50000000e+01 3.00000000e+00 6.50000000e+01 4.61538462e-02
  1.03846154e-01]
 [1.20000000e+01 5.00000000e+00 6.80000000e+01 7.35294118e-02
  4.41176471e-02]]


In [30]:
# Calcula el nuevo salario = salario + bonificación
nuevoSalario = arraySalario+bonificacion
datosEmpleados = np.stack((arraySalario,arrayProyecto,arrayHora,productividad,bonificacion,nuevoSalario),axis=1)
print(datosEmpleados)

[[3.40000000e+01 9.00000000e+00 5.00000000e+00 1.80000000e+00
  3.06000000e+00 3.70600000e+01]
 [9.60000000e+01 4.00000000e+00 1.70000000e+01 2.35294118e-01
  1.12941176e+00 9.71294118e+01]
 [5.20000000e+01 1.00000000e+00 5.00000000e+01 2.00000000e-02
  5.20000000e-02 5.20520000e+01]
 ...
 [4.10000000e+01 4.00000000e+00 5.50000000e+01 7.27272727e-02
  1.49090909e-01 4.11490909e+01]
 [4.50000000e+01 3.00000000e+00 6.50000000e+01 4.61538462e-02
  1.03846154e-01 4.51038462e+01]
 [1.20000000e+01 5.00000000e+00 6.80000000e+01 7.35294118e-02
  4.41176471e-02 1.20441176e+01]]


In [33]:
#4. Calcula: 
# o La media y desviación estándar del nuevo salario
mediaSalario = np.mean(nuevoSalario)
print(mediaSalario)

# o La correlación entre salarios y productividad
correlacionSalProd = np.corrcoef(arraySalario,productividad)
print(correlacionSalProd)

50.774633312626584
[[ 1.00000000e+00 -3.77772778e-04]
 [-3.77772778e-04  1.00000000e+00]]


In [35]:
#Combina las columnas en un solo array 2D (salario, productividad, nuevo salario)
salarioProductividadNuevSalario = np.hstack((arraySalario, productividad,nuevoSalario))
print(salarioProductividadNuevSalario)

[34.         96.         52.         ... 41.14909091 45.10384615
 12.04411765]


## 6. Explica qué es el coeficiente de correlación de Pearson y qué sentido tiene aplicarlo en el apartado 4 de este ejercicio. Además de eso, explica qué información aporta.
#### Medida estadística que cuantifica la fuerza y dirección de la relación lineal entre dos variables cuantitativas. Esto mide si esos datos tienen una asociación lineal

### EJERCICIO 12 -Temperaturas y vendimia

In [8]:
# -------------------------------------------------------------
# 1️⃣ Datos originales (lista proporcionada)
# -------------------------------------------------------------
temperaturas = [
    21.3, 17.1, 22.5, 28.7, 16.0, 16.4, 29.3, 24.1, 15.2, 22.9, 14.4, 15.2, 19.8, 5.7,
    5.5, 13.6, 10.6, 19.1, 11.4, 7.7, 28.3, 16.6, 19.4, 8.5, 13.9, 18.3, 10.2, 20.0,
    14.7, 16.5, 13.6, 30.1, 18.6, 10.5, 24.4, 8.7, 19.2, 4.3, 8.7, 19.2, 23.5, 18.7,
    17.1, 16.0, 7.9, 13.3, 14.2, 24.6, 21.0, 5.8, 19.9, 16.1, 13.3, 22.9, 25.3, 25.5,
    13.0, 15.7, 20.8, 25.2, 15.3, 16.2, 10.6, 10.2, 22.8, 26.9, 16.5, 24.9, 20.9, 14.2,
    20.6, 29.6, 17.1, 28.1, 0.0, 23.9, 18.6, 14.9, 18.6, 3.4, 16.8, 20.7, 27.9, 14.1,
    11.8, 14.5, 24.9, 19.8, 14.5, 21.3, 18.3, 24.7, 12.6, 15.4, 14.7, 8.7, 20.1, 19.5,
    18.1, 16.3, 8.0, 15.4, 16.0, 12.1, 16.6, 20.7, 30.1, 18.5, 20.5, 18.3, 4.4, 18.1,
    18.6, 36.8, 17.2, 20.0, 17.3, 9.0, 26.1, 22.9, 22.8, 11.3, 27.3, 9.0, 22.5, 33.3,
    11.8, 14.1, 18.3, 15.2, 7.4, 18.0, 10.5, 20.9, 10.9, 29.3, 13.5, 15.0, 24.0, 9.1,
    19.3, 26.9, 6.3, 19.3, 19.4, 23.6, 9.3, 8.6, 21.2, 19.8, 20.1, 20.7, 12.8, 19.7,
    20.4, 12.2, 31.3, 21.0, 9.9, 22.2, 10.3, 22.7, 26.1, 12.4, 24.3, 21.2, 22.9, 31.2,
    15.7, 12.4, 11.8, 11.9, 17.3, 20.9, 19.6, 24.2, 17.5, 28.4, 16.9, 35.8, 22.0, 12.3,
    10.4, 21.6, 16.1, 23.0, 21.2, 18.1, 12.2, 7.6, 14.7, 23.8, 19.3, 9.5, 19.0, 20.8,
    12.9, 19.5, 18.2, 10.6, 20.3, 20.9, 25.1, 24.4, 8.2, 11.4, 22.4, 21.8, 21.5, 40.0,
    20.9, 26.1, 25.1, 21.8, 16.4, 23.5, 12.4, 16.7, 15.7, 18.7, 34.3, 4.7, 22.4, 7.1,
    14.3, 25.7, 18.2, 10.7, 13.2, 23.3, 12.6, 19.4, 17.8, 13.2, 33.2, 22.8, 3.4, 19.7,
    14.0, 24.2, 13.4, 16.8, 20.9, 23.2, 10.3, 16.0, 14.6, 13.6, 29.8, 22.1, 9.2, 24.5,
    33.2, 25.5, 7.5, 14.2, 27.1, 14.0, 21.8, 24.2, 11.3, 17.1, 0.0, 10.9, 16.8, 8.4,
    30.2, 7.9, 14.7, 18.4, 27.3, 8.4, 26.2, 17.4, 10.5, 21.1, 20.2, 13.7, 17.7, 15.2,
    18.7, 21.3, 29.1, 9.2, 33.3, 5.3, 17.5, 22.0, 19.4, 14.9, 16.6, 14.6, 13.9, 24.0,
    20.4, 12.9, 24.0, 20.1, 23.4, 22.1, 12.3, 14.0, 24.0, 20.9, 18.4, 19.4, 25.9, 13.7,
    21.6, 15.9, 16.1, 25.1, 24.7, 24.2, 27.8, 18.5, 22.2, 15.6, 20.5, 16.5, 19.0, 22.0,
    12.1, 33.0, 11.2, 9.3, 26.7, 23.0, 22.7, 22.7, 17.8, 11.9, 17.9, 13.7, 24.7, 16.7,
    12.7, 15.4, 20.2, 13.3, 12.5, 19.1, 20.6, 13.4, 15.6, 19.7, 7.8, 7.9, 13.2, 16.5,
    20.7, 28.4, 24.1, 16.7, 17.8, 11.1, 17.0, 15.3, 20.6, 12.3, 21.5, 28.7, 17.4, 20.5,
    22.4
]

In [6]:
#1. Calcula:
# La temperatura media anual.
# El día más cálido y el día más frío del año.
media = np.mean(temperaturas)
print(media)
maxT = np.max(temperaturas)
print(maxT)
minT = np.min(temperaturas)
print(minT)

18.05123287671233
40.0
0.0


In [13]:
#2. Determina:
# Cuántos días tuvieron una temperatura media superior a 25°C.
# Cuántos días superaron los 35 °C.
arrayTemp=np.array(temperaturas)
mas25=np.sum(arrayTemp>25)
print(mas25)
mas35=np.sum(arrayTemp>35)
print(mas35)


46
3


In [ ]:
#Identifica el primer día del año en el que se registran 5 días consecutivos con temperatura media superior a 25 °C,
#y considera ese día como el inicio óptimo de la vendimia. 
diauno=25

