# 1.- Funciones útiles que permiten generar arrays 

In [1]:
import numpy as np

In [2]:
#  1. Crear un array a partir de una lista
arr1 = np.array([1, 2, 3, 4, 5])
print("Array desde lista:", arr1)

Array desde lista: [1 2 3 4 5]


In [3]:
# 2. Array de ceros (3 filas x 4 columnas)
arr2 = np.zeros((3, 4))
print("\nArray de ceros (3x4):\n", arr2)


Array de ceros (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
# 3. Array de unos (2 filas x 3 columnas)
arr3 = np.ones((2, 3))
print("\nArray de unos (2x3):\n", arr3)


Array de unos (2x3):
 [[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
# 4. Array lleno con un valor (7 en este caso)
arr4 = np.full((2, 2), 7)
print("\nArray lleno de 7:\n", arr4)


Array lleno de 7:
 [[7 7]
 [7 7]]


In [6]:
# 5. Secuencia con np.arange (inicio=0, fin=10, paso=2)
arr5 = np.arange(0, 10, 2)
print("\nArray con arange (0 a 10, paso 2):", arr5)


Array con arange (0 a 10, paso 2): [0 2 4 6 8]


In [7]:
# 6. Secuencia con np.linspace (5 valores entre 0 y 1)
arr6 = np.linspace(0, 1, 5)
print("\nArray con linspace (5 valores entre 0 y 1):", arr6)


Array con linspace (5 valores entre 0 y 1): [0.   0.25 0.5  0.75 1.  ]


In [8]:
# 7. Números enteros aleatorios entre 10 y 20 (tamaño 5)
arr7 = np.random.randint(10, 20, size=5)
print("\nEnteros aleatorios entre 10 y 20:", arr7)


Enteros aleatorios entre 10 y 20: [18 19 18 18 13]


In [9]:
# 8. Números decimales aleatorios entre 1.0 y 5.0 (tamaño 4)
arr8 = np.random.uniform(1.0, 5.0, size=4)
print("\nFlotantes aleatorios entre 1.0 y 5.0:", arr8)


Flotantes aleatorios entre 1.0 y 5.0: [4.34205962 3.95184825 1.2337937  1.51915657]


# 2.-Información sobre el array creado

In [11]:
import numpy as np

# Array unidimensional
x = np.array([1, 2, 3, 4, 5])
print("Datos:", x)              # Los datos del array
print("Dimensión:", x.ndim)     # Nº de dimensiones (1 → vector)
print("Tamaño total:", x.size)  # Nº de elementos (5 en este caso)
print("Forma:", x.shape)        # (5,) → 1 fila con 5 elementos
print("Tipo de datos:", x.dtype) # Tipo de cada elemento (por defecto int64 o int32 según SO)

Datos: [1 2 3 4 5]
Dimensión: 1
Tamaño total: 5
Forma: (5,)
Tipo de datos: int64


In [12]:
# Array bidimensional (matriz 2x4)
x = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8]])
print("\nDatos:\n", x)
print("Dimensión:", x.ndim)     # Nº de dimensiones (2 → matriz)
print("Tamaño total:", x.size)  # Nº total de elementos (2x4 = 8)
print("Forma:", x.shape)        # (2, 4) → 2 filas y 4 columnas
print("Tipo de datos:", x.dtype)


Datos:
 [[1 2 3 4]
 [5 6 7 8]]
Dimensión: 2
Tamaño total: 8
Forma: (2, 4)
Tipo de datos: int64


In [13]:
# Cambiar la forma de un array con reshape
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print("\nArray original:", a)

# Convertir a una matriz de 3 filas y 4 columnas
print("\nReshape a (3,4):\n", np.reshape(a, (3, 4)))

# Convertir a 6 filas y columnas automáticas (-1 → que NumPy calcule)
print("\nReshape a (6, -1):\n", np.reshape(a, (6, -1)))

# Convertir a columnas fijas (=3) y filas automáticas
print("\nReshape a (-1, 3):\n", np.reshape(a, (-1, 3)))


Array original: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshape a (3,4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshape a (6, -1):
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

Reshape a (-1, 3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
# Error: 12 elementos no se pueden repartir en columnas de 5
try:
    np.reshape(a, (-1, 5))
except ValueError as e:
    print("\nERROR con reshape (-1,5):", e)


ERROR con reshape (-1,5): cannot reshape array of size 12 into shape (5)


# 3.- Constantes predefinidas

In [15]:
import numpy as np

In [17]:
# Infinito positivo
print(np.inf)        # Representa +∞
print(10/0.0000001)  # Ejemplo: un número muy grande se aproxima a infinito

inf
100000000.0


In [23]:
# No es un número (NaN)
print(np.nan)        # Resultado indefinido
print(0/np.inf)      # Ejemplo: 0 dividido entre infinito → NaN

nan
0.0


In [20]:
# Constante e (≈2.718)
print(np.e)          # Base de logaritmos naturales
print(np.exp(1))     # exp(1) = e^1 = e


2.718281828459045
2.718281828459045


In [21]:
# Constante pi (≈3.1416)
print(np.pi)         # Relación circunferencia/diámetro
print(2 * np.pi * 5) # Longitud de circunferencia de radio 5

3.141592653589793
31.41592653589793


# 4.- Funciones predefinidas para la creación de arrays

## Arrays de ceros

In [24]:
import numpy as np

In [25]:
# ------------------------------
# ARRAYS DE CEROS
# ------------------------------
print(np.zeros((3, 4)))         
# Crea un array de 3 filas y 4 columnas con ceros (por defecto tipo float)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
print(np.zeros((3, 4), dtype=int))  
# Lo mismo, pero especificando que sean enteros

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


## Arrays de ceros con la forma de otro array

In [27]:
# ------------------------------
# ARRAYS DE CEROS CON LA FORMA DE OTRO ARRAY
# ------------------------------
M = np.array([[1, 2, 3], [4, 5, 6]])  
print(np.zeros_like(M))       
# Crea un array de ceros con la misma forma que M (2 filas, 3 columnas)

[[0 0 0]
 [0 0 0]]


## Arrays de unos

In [28]:
# ------------------------------
# ARRAYS DE UNOS
# ------------------------------
print(np.ones((3, 4)))        
# Array de 3 filas y 4 columnas relleno de unos
# También existe np.ones_like(M)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Arrays relleno con un valor

In [29]:
# ------------------------------
# ARRAY RELLENO CON UN VALOR
# ------------------------------
print(np.full((3, 4), 7))     
# Crea un array 3x4 con todos sus elementos = 7
# También existe np.full_like(M, 7)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


## Matriz identidad

In [31]:
# ------------------------------
# MATRIZ IDENTIDAD
# ------------------------------
print(np.eye(5))              
# Matriz identidad de 5x5 → unos en la diagonal principal y ceros en el resto

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Matriz diagonal

In [32]:
# ------------------------------
# MATRIZ DIAGONAL
# ------------------------------
print(np.diag([1, 4, 6, 9]))  
# Crea una matriz cuadrada con los valores dados en la diagonal principal

[[1 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 9]]


# 5.- Crear arrays con valores enteros equiespaciados, función Arange()

In [33]:
import numpy as np

In [34]:
print(np.arange(21))          
# Array de 21 elementos: desde 0 hasta 20 (paso = 1 por defecto)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [35]:
print(np.arange(6, 60))       
# Array desde 6 hasta 59 (60 no se incluye), paso = 1
# Tiene 54 elementos

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]


In [36]:
print(np.arange(6, 60, 3))    
# Array desde 6 hasta 57 (60 no se incluye), de 3 en 3
# [6, 9, 12, ..., 57]

[ 6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57]


In [37]:
print(np.arange(6, 60, 0.3))  
# Array desde 6.0 hasta 59.7 (60 no se incluye), paso = 0.3 (decimal)

[ 6.   6.3  6.6  6.9  7.2  7.5  7.8  8.1  8.4  8.7  9.   9.3  9.6  9.9
 10.2 10.5 10.8 11.1 11.4 11.7 12.  12.3 12.6 12.9 13.2 13.5 13.8 14.1
 14.4 14.7 15.  15.3 15.6 15.9 16.2 16.5 16.8 17.1 17.4 17.7 18.  18.3
 18.6 18.9 19.2 19.5 19.8 20.1 20.4 20.7 21.  21.3 21.6 21.9 22.2 22.5
 22.8 23.1 23.4 23.7 24.  24.3 24.6 24.9 25.2 25.5 25.8 26.1 26.4 26.7
 27.  27.3 27.6 27.9 28.2 28.5 28.8 29.1 29.4 29.7 30.  30.3 30.6 30.9
 31.2 31.5 31.8 32.1 32.4 32.7 33.  33.3 33.6 33.9 34.2 34.5 34.8 35.1
 35.4 35.7 36.  36.3 36.6 36.9 37.2 37.5 37.8 38.1 38.4 38.7 39.  39.3
 39.6 39.9 40.2 40.5 40.8 41.1 41.4 41.7 42.  42.3 42.6 42.9 43.2 43.5
 43.8 44.1 44.4 44.7 45.  45.3 45.6 45.9 46.2 46.5 46.8 47.1 47.4 47.7
 48.  48.3 48.6 48.9 49.2 49.5 49.8 50.1 50.4 50.7 51.  51.3 51.6 51.9
 52.2 52.5 52.8 53.1 53.4 53.7 54.  54.3 54.6 54.9 55.2 55.5 55.8 56.1
 56.4 56.7 57.  57.3 57.6 57.9 58.2 58.5 58.8 59.1 59.4 59.7]


# 6.- Valores flotantes equiespaciados

In [38]:
import numpy as np

In [39]:
print(np.linspace(6, 60))  
# Por defecto genera 50 valores entre 6 y 60 (ambos incluidos)

[ 6.          7.10204082  8.20408163  9.30612245 10.40816327 11.51020408
 12.6122449  13.71428571 14.81632653 15.91836735 17.02040816 18.12244898
 19.2244898  20.32653061 21.42857143 22.53061224 23.63265306 24.73469388
 25.83673469 26.93877551 28.04081633 29.14285714 30.24489796 31.34693878
 32.44897959 33.55102041 34.65306122 35.75510204 36.85714286 37.95918367
 39.06122449 40.16326531 41.26530612 42.36734694 43.46938776 44.57142857
 45.67346939 46.7755102  47.87755102 48.97959184 50.08163265 51.18367347
 52.28571429 53.3877551  54.48979592 55.59183673 56.69387755 57.79591837
 58.89795918 60.        ]


In [40]:
print(np.linspace(6, 60, 20))  
# Genera 20 valores equidistantes entre 6 y 60 (ambos incluidos)

[ 6.          8.84210526 11.68421053 14.52631579 17.36842105 20.21052632
 23.05263158 25.89473684 28.73684211 31.57894737 34.42105263 37.26315789
 40.10526316 42.94736842 45.78947368 48.63157895 51.47368421 54.31578947
 57.15789474 60.        ]


In [41]:
print(np.linspace(6, 60, 20, endpoint=False))  
# Genera 20 valores entre 6 y 60 (pero 60 no se incluye, intervalo abierto)

[ 6.   8.7 11.4 14.1 16.8 19.5 22.2 24.9 27.6 30.3 33.  35.7 38.4 41.1
 43.8 46.5 49.2 51.9 54.6 57.3]


# 7.- Valores aleatorios enteros

In [42]:
import numpy as np

In [43]:
# ------------------------------
# VALORES ALEATORIOS ENTEROS
# ------------------------------
print(np.random.randint(3, 30))  
# Un número aleatorio entero entre 3 y 30 (30 no incluido)

26


In [44]:
print(np.random.randint(3, 30, size=9))  
# Array de 9 enteros aleatorios entre 3 y 30

[16 28 27  3  9 14 17  6 24]


In [45]:
print(np.random.randint(3, 30, size=(3, 3)))  
# Matriz 3x3 de enteros aleatorios entre 3 y 30

[[14 13 18]
 [14 24 13]
 [17 29 12]]


# 8.- Valores aleatorios flotantes

In [46]:
# ------------------------------
# VALORES ALEATORIOS FLOTANTES
# ------------------------------
print(np.random.random(9))  
# Array de 9 valores aleatorios flotantes entre 0 y 1

[0.19074745 0.15394778 0.76996521 0.87424196 0.02706739 0.73182749
 0.7290455  0.41888202 0.05091323]


In [47]:
print(np.random.uniform(1, 100, size=9))  
# Array de 9 valores aleatorios flotantes entre 1 y 100

[39.54091784 84.86872628 84.7322401  30.10315742 58.39611915 78.74346822
 20.01346495 51.09861332 32.89437237]


# 9.- Distribución normal

In [48]:
# ------------------------------
# DISTRIBUCIÓN NORMAL
# ------------------------------
# np.random.normal(media, desviación, tamaño)
dist = np.random.normal(0, 5, size=1000)  
# Genera 1000 valores distribuidos normalmente con media=0 y σ=5

In [50]:
print(dist[:10])       # Muestra los 10 primeros valores

[ 3.63560326  5.47795631  0.88963573  0.17405961 -5.69743895 -7.05719338
 -2.92995831 -2.39647511 -1.03187249 -2.7675292 ]


In [51]:
print(dist.mean())     # Media aproximada (cercana a 0)

0.253821960183131


In [52]:
print(dist.std())      # Desviación estándar aproximada (cercana a 5)

4.695731866363901


# 10.- Manipulando arrays Numpys 

## Arrays de 1 dimensión (vectores)

In [53]:
import numpy as np

In [54]:
# ---------------------------------
# 1D → ARRAYS DE UNA DIMENSIÓN
# ---------------------------------
v = np.array([10, 20, 30, 40])

print(v[0])    # Primer elemento (índice 0) → 10
print(v[1])    # Segundo elemento (índice 1) → 20
print(v[-1])   # Último elemento (índice -1) → 40
print(v[-2])   # Penúltimo elemento (índice -2) → 30

10
20
40
30


## Arrays de 2 dimensiones (matrices)

In [55]:
# ---------------------------------
# 2D → ARRAYS DE DOS DIMENSIONES (MATRICES)
# ---------------------------------
m = np.array([[1, 2, 3], [4, 5, 6]])

print(m[0, 0])  # Elemento fila 0, columna 0 → 1
print(m[0, 2])  # Elemento fila 0, columna 2 → 3
print(m[1, 1])  # Elemento fila 1, columna 1 → 5
print(m[1, 2])  # Elemento fila 1, columna 2 → 6


1
3
5
6


## Arrays de 3 o más dimensiones

In [56]:
# ---------------------------------
# 3D → ARRAYS DE TRES DIMENSIONES (CUBOS)
# ---------------------------------
cubo = np.array([
    [[1, 2], [3, 4]],   # Primer bloque (profundidad 0)
    [[5, 6], [7, 8]]    # Segundo bloque (profundidad 1)
])

print(cubo[0, 0, 0])  # Primer bloque, fila 0, col 0 → 1
print(cubo[0, 1, 1])  # Primer bloque, fila 1, col 1 → 4
print(cubo[1, 0, 1])  # Segundo bloque, fila 0, col 1 → 6
print(cubo[1, 1, 0])  # Segundo bloque, fila 1, col 0 → 7

1
4
6
7


# 11.-Acceder, borrar, y añadir a un array 1D

In [58]:
import numpy as np

In [59]:
# Creamos un array 1D
datos = np.array([10, 11, 12, 13, 14, 15])
print("Array original:", datos)

Array original: [10 11 12 13 14 15]


## Acceder a elementos

In [60]:
print(datos[0])      # Primer elemento → 10
print(datos[-2])     # Penúltimo elemento → 14
print(datos[[0, 2, 5]])  # Varias posiciones → [10 12 15]

print(datos[:4])     # Primeros 4 → [10 11 12 13]
print(datos[1:-2])   # Del índice 1 al -2 → [11 12 13]
print(datos[3:])     # Desde índice 3 hasta el final → [13 14 15]

print(datos[1::3])   # Desde índice 1 de 3 en 3 → [11 14]
print(datos[::2])    # De 2 en 2 → [10 12 14]
print(datos[1::2])   # Desde 1 de 2 en 2 → [11 13 15]

10
14
[10 12 15]
[10 11 12 13]
[11 12 13]
[13 14 15]
[11 14]
[10 12 14]
[11 13 15]


## Modificar elementos

In [61]:
datos[0] = 100              # Reemplaza el primer valor
datos[3] = datos[5] + datos[1]  # Usa otros valores para calcular
print("Array modificado:", datos)

Array modificado: [100  11  12  26  14  15]


## Borrar elementos

In [62]:
# Crear array de nuevo
datos = np.array([10, 11, 12, 13, 14, 15])

In [63]:
# Eliminar el elemento en la posición 2
datos = np.delete(datos, 2)
print("Borrando índice 2:", datos)

Borrando índice 2: [10 11 13 14 15]


In [64]:
# Eliminar varios elementos (posiciones 1, 3 y 4)
datos = np.delete(datos, (1, 3, 4))
print("Borrando índices 1,3,4:", datos)

Borrando índices 1,3,4: [10 13]


## Añadir elementos

In [65]:
datos = np.array([10, 11, 12, 13, 14, 15])

In [66]:
# Añadir con append
datos = np.append(datos, [16, 17, 18])  # Agregar varios al final
datos = np.append(datos, 40)            # Agregar un único valor
print("Con append:", datos)

Con append: [10 11 12 13 14 15 16 17 18 40]


In [67]:
# Añadir con insert
datos = np.insert(datos, 1, 101)  # Insertar en la posición 1
datos = np.insert(datos, 8, 88)   # Insertar en la posición 8
print("Con insert:", datos)

Con insert: [ 10 101  11  12  13  14  15  16  88  17  18  40]


## Recorrer un array

In [68]:
for i in range(len(datos)):
    print("Índice", i, "→", datos[i])

Índice 0 → 10
Índice 1 → 101
Índice 2 → 11
Índice 3 → 12
Índice 4 → 13
Índice 5 → 14
Índice 6 → 15
Índice 7 → 16
Índice 8 → 88
Índice 9 → 17
Índice 10 → 18
Índice 11 → 40


# 12.- Unir dos arrays y separarlos

In [70]:
import numpy as np

In [71]:
# Creamos dos arrays de ejemplo: alturas y pesos
altura = np.array([1.74, 1.8, 1.78, 1.68, 1.78])
peso   = np.array([81.4, 88.7, 87.3, 62.7, 81.6])

In [74]:
altura

array([1.74, 1.8 , 1.78, 1.68, 1.78])

In [75]:
peso

array([81.4, 88.7, 87.3, 62.7, 81.6])

## Unir arrays con np.stack()

In [72]:
# Unir como filas (axis=0, por defecto)
# Resultado: un array 2D donde altura está en la fila 0 y peso en la fila 1
union1 = np.stack((altura, peso))
print(union1)

[[ 1.74  1.8   1.78  1.68  1.78]
 [81.4  88.7  87.3  62.7  81.6 ]]


In [73]:
# Unir como columnas (axis=1)
# Resultado: un array 2D donde cada fila es [altura, peso]
union2 = np.stack((altura, peso), axis=1)
print(union2)

[[ 1.74 81.4 ]
 [ 1.8  88.7 ]
 [ 1.78 87.3 ]
 [ 1.68 62.7 ]
 [ 1.78 81.6 ]]


## Unir arrays con np.concatenate()

In [76]:
# Concatena los dos arrays en una sola dimensión (1D)
concatenar = np.concatenate((altura, peso))
print(concatenar)

[ 1.74  1.8   1.78  1.68  1.78 81.4  88.7  87.3  62.7  81.6 ]


## Separar arrays con np.split()

In [77]:
# Dividir union1 en 2 arrays (altura y peso por separado)
separados1 = np.split(union1, 2)
print(separados1)

[array([[1.74, 1.8 , 1.78, 1.68, 1.78]]), array([[81.4, 88.7, 87.3, 62.7, 81.6]])]


In [78]:
# Dividir union2 en 5 arrays (cada persona con altura y peso)
separados2 = np.split(union2, 5)
print(separados2)

[array([[ 1.74, 81.4 ]]), array([[ 1.8, 88.7]]), array([[ 1.78, 87.3 ]]), array([[ 1.68, 62.7 ]]), array([[ 1.78, 81.6 ]])]


# 13.- Acceso y manipulación de arrays 2D

## Crear y acceder a elementos

In [82]:
import numpy as np

In [83]:
# Crear un array 2D de 3x4 con valores del 10 al 21
datos = np.arange(10, 22).reshape(3, 4)
print(datos)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [84]:
# Acceder a un elemento (fila 0, columna 1 → valor 11)
print(datos[0, 1])

11


In [85]:
# Acceder al último elemento
print(datos[-1, -1])

21


In [86]:
# Acceder a una fila completa (fila 0)
print(datos[0, :])

[10 11 12 13]


In [87]:
# Acceder a una columna completa (columna 1)
print(datos[:, 1])

[11 15 19]


## Recorrer un array 2D

In [88]:
# Recorremos todas las filas y columnas
for i in range(len(datos)):
    for j in range(len(datos[i])):
        print("Fila", i, "Columna", j, "=", datos[i][j])

Fila 0 Columna 0 = 10
Fila 0 Columna 1 = 11
Fila 0 Columna 2 = 12
Fila 0 Columna 3 = 13
Fila 1 Columna 0 = 14
Fila 1 Columna 1 = 15
Fila 1 Columna 2 = 16
Fila 1 Columna 3 = 17
Fila 2 Columna 0 = 18
Fila 2 Columna 1 = 19
Fila 2 Columna 2 = 20
Fila 2 Columna 3 = 21


## Copiar y modificar datos

In [90]:
# Copiar array
copia = np.copy(datos)

In [91]:
# Modificar una fila completa (fila 1)
datos[1] = [55, 66, 77, 88]
print(datos)

[[ 10  11  30  13]
 [ 55  66  77  88]
 [ 18  19 110  21]]


In [92]:
# Modificar una columna completa (columna 2)
datos[:, 2] = [30, 70, 110]
print(datos)

[[ 10  11  30  13]
 [ 55  66  70  88]
 [ 18  19 110  21]]


# 14.- Borrar e insertar filas/columnas

## Borrar filas/columnas

In [93]:
# Volvemos al array original
datos = np.copy(copia)

In [94]:
# Borrar la fila 1
datos = np.delete(datos, 1, axis=0)
print(datos)

[[ 10  11  30  13]
 [ 18  19 110  21]]


In [95]:
# Borrar las columnas 1 y 3
datos = np.delete(datos, (1, 3), axis=1)
print(datos)

[[ 10  30]
 [ 18 110]]


## Insertar filas/columnas

In [96]:
# Insertar una fila en la posición 2
datos = np.copy(copia)
datos = np.insert(datos, 2, [3, 3, 3, 3], axis=0)
print(datos)

[[ 10  11  30  13]
 [ 55  66  70  88]
 [  3   3   3   3]
 [ 18  19 110  21]]


In [98]:
# Insertar una columna en la posición 0
datos = np.insert(datos, 0, [9, 9, 9, 9], axis=1)
print(datos)

[[  9  10  11  30  13]
 [  9  55  66  70  88]
 [  9   3   3   3   3]
 [  9  18  19 110  21]]


# 15.- Trasponer una matriz

In [100]:
# La traspuesta intercambia filas ↔ columnas
a = np.array([[1, 2], [3, 4], [5, 6]])
print("Original:\n", a)
print("Traspuesta:\n", a.T)


Original:
 [[1 2]
 [3 4]
 [5 6]]
Traspuesta:
 [[1 3 5]
 [2 4 6]]


# 16.- Condiciones. Indexado booleano

In [101]:
datos = np.array([[60, 47, 34], [43, 63, 37], [58, 28, 31]])

In [102]:
# Ver qué elementos son mayores de 50
print(datos > 50)

[[ True False False]
 [False  True False]
 [ True False False]]


In [103]:
# Filtrar: mostrar solo los que son mayores de 50
print(datos[datos > 50])

[60 63 58]


In [104]:
# Modificar: poner -1 en todos los mayores de 50
datos[datos > 50] = -1
print(datos)

[[-1 47 34]
 [43 -1 37]
 [-1 28 31]]


# 17.- Ordenar un array

In [105]:
import numpy as np

In [106]:
datos = np.array([[52, 23, 90],
                  [61, 63, 74]])

In [107]:
# Ordenar filas (cada fila de menor a mayor)
print(np.sort(datos, axis=1))

[[23 52 90]
 [61 63 74]]


In [108]:
# Ordenar columnas (cada columna de menor a mayor)
print(np.sort(datos, axis=0))

[[52 23 74]
 [61 63 90]]


# 18.- Operaciones aritméticas

In [110]:
#Operaciones aritméticas
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [111]:
# Sumar
print(a + b)

[[ 6  8]
 [10 12]]


In [112]:
# Restar
print(a - b)

[[-4 -4]
 [-4 -4]]


In [113]:
# Multiplicar elemento a elemento
print(a * b)

[[ 5 12]
 [21 32]]


In [114]:
# Dividir
print(a / b)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [115]:
# Sumar un número a todos los elementos
print(a + 10)

[[11 12]
 [13 14]]


# 19.- Funciones estadísticas

In [116]:
import numpy as np

In [117]:
datos = np.array([[1, 2],
                  [3, 4],
                  [5, 6]])

In [118]:
# Máximo y mínimo
print("Máximo:", datos.max())   # 6
print("Mínimo:", datos.min())   # 1

Máximo: 6
Mínimo: 1


In [119]:
# Suma total y media
print("Suma:", datos.sum())     # 21
print("Media:", datos.mean())   # 3.5

Suma: 21
Media: 3.5


In [120]:
# Operar por filas y columnas
print("Suma por filas:", datos.sum(axis=1))   # [ 3  7 11 ]
print("Suma por columnas:", datos.sum(axis=0))# [ 9 12 ]

Suma por filas: [ 3  7 11]
Suma por columnas: [ 9 12]
